# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Guilherme Araújo
description: > # this means to ignore newlines until "baseurl:"
  Mobile Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.guilhermearaujo.me" # the base hostname & protocol for your site

github_username:  guilhermearaujo

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/guilhermearaujo
  - title: linkedin
    url: http://br.linkedin.com/in/guilhermeamaraujo
  - title: stack-overflow
    url: http://stackoverflow.com/users/1262783/guilherme

# Build settings
markdown: kramdown
permalink: pretty
